name: Check Pint

on:
  pull_request:
    branches: [ main, development ]

jobs:
  check-pint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      # - name: Run PHPStan
      #   run: vendor/bin/phpstan analyse

      - name: Install Laravel Pint
        run: composer require laravel/pint --dev

      - name: Run Laravel Pint
        run: vendor/bin/pint